services:
  db:
    image: mysql:8.0
    container_name: notes-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend/notes-app-backend
    container_name: notes-backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/notes_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_FORWARD_HEADERS_STRATEGY=NATIVE
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend/notes-app-frontend
    container_name: notes-frontend
    ports:
      - "5173:80"

volumes:
  mysql_data: